name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
        
    - name: Install dependencies
      run: echo "No need to install anything. Just build and push the Docker image."

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        echo "Inside the Build and push Docker image step"
        docker --version # print the version for logging
        docker build -t lcd1502/sample-express-app .
        docker tag lcd1502/sample-express-app lcd1502/sample-express-app:1.0.0
        docker push lcd1502/sample-express-app:1.0.0
